name: Request Build
on:
  push:
    branches:
      - main
      - dev
jobs:
  request-build:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DODOCO_BOT_PAT }}
          repository: hu-tao-supremacy/deploys
          event-type: request-build
          client-payload: '{ "repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'
